fixing releasing 12

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,7 @@
 sudo: false
 language: java
 jdk:
-- oraclejdk8
+- openjdk8
 
 before_cache:
   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
@@ -11,7 +11,23 @@ cache:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/wrapper/
 
+script: 
+# build fat jar
 - ./gradlew export.prepareEclipseInstaller
+
+# prepare OomphInstallers (workaround for a non-zero exit code appended)
+- >
+  export version=`grep "base.version" cnf/build.bnd |cut -d'=' -f2`;
+  export currDate=`date +'%Y%m%d-%H%M%S'`;
+  export gitTag=$(git log --format=%h -1);
+  export snapshot=".SNAPSHOT";
+  export prerelease=true;
+  export TRAVIS_TAG=${version}.${currDate}_${gitTag}${snapshot};
+  echo "TRAVIS_TAG=${TRAVIS_TAG}";
+  env | sort
+#  java 
+#  -Dtimestamp=${currDate} 
+#  -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar || true
 
 before_deploy:
 # Set up git user name and tag this commit
@@ -22,18 +38,14 @@ before_deploy:
     export prerelease=false; 
     export snapshot="";
   fi
-  export version=`grep "base.version" cnf/build.bnd |cut -d'=' -f2`;
-  export currDate=`date +'%Y%m%d-%H%M%S'`;
-  export gitTag=$(git log --format=%h -1);
-  export snapshot=".SNAPSHOT";
-  export prerelease=true;
-  export TRAVIS_TAG=${version}.${currDate}_${gitTag}${snapshot};
-  export RELEASE="IDEfix"
-  export RELEASE_NAME="$RELEASE $TRAVIS_TAG"
-  export RELEASE_CONTENT="t.b.d. - $RELEASE"
-  java 
-  -Dtimestamp=${currDate} 
-  -jar io.klib.prepare.eclipseinstaller/generated/distributions/executable/prepareEclipseInstaller.jar || true
+- export TRAVIS_TAG=${version}.${currDate}_${gitTag}${snapshot}
+- git tag $TRAVIS_TAG
+
+# release 
+- export RELEASE="IDEfix"
+- export RELEASE_NAME="$RELEASE $TRAVIS_TAG"
+- export RELEASE_CONTENT="t.b.d. - $RELEASE"
+- echo "creating deployment for $RELEASE_NAME with $TRAVIS_TAG"
 
 deploy:
   provider: releases
@@ -41,7 +53,7 @@ deploy:
   api_key:
     secure: In29qlp4RJ9P8Lo4dEZQCKWwaLGzVul/ElMf4kLdOg0MJBtVyTstMR+R61AfCM66VMeF2B1M2McadjOd5d2GWx8cWgPs5bR5tJJZuqztEX2aZYVj/OBO51vhHy3xFuS525JouzomVIuVeOXVIcEl0MarVKdU4lCMuAO8umJlprRJRNRo26B5iYQ2O06V11CxrLMWOfJM6eay7NdX2/W9LcchX7+aqvacjsJ7MX5KsA00AQjRZ9Mzv9nH0YJa6wAL+jDud0IIW1BE3+7IGeAovDwTjMXZY587BPQHFZS0+IBg5NR2qCK2uVVRx3L5qVEOUAEjIuU2I0LB8N4qWBcIEk4pfZXear9SfGm7W8b1PviwSdafmz6BdlQqPALlDfs/Pp+Z9bdU6jRR4H5GQg0dDp6KnO6P6ofuvNirb2JmygOGNC+cuTbgb5oIKfjcIgw5D/MCiJOntiPwUV4WyiewpzHY6mc4kUpRIXZe2T+ZK3UQzyf+JGpTmkKLOnNQ9xXXjJvaEgd8qGa0qX5ATWxZV4Y1KRH9pH0I6CZ+WrqjYM4Sj4aexamPp+PQPnHt7o6gnRy2Bnoz80vEVXoYKtMIwft4IJDvwc70UjUO7auPOzwHCLH7dAZ8YGey5D7wwU0tp3xk5NyDCm6NSRFrfN+tukz9RYwqI2skewIpLPIrJlE=
   file_glob: true
-  file: _result/$currDate
+  file: _result/$DATE/$RELEASE/*
   skip_cleanup: true
   on:
     all_branches: true
